FROM almalinux:9
RUN dnf install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
ADD https://raw.githubusercontent.com/saikirangoka/Docker/refs/heads/main/COPY/Dockerfile /usr/share/nginx/html/index.html
RUN chmod +r
CMD ["nginx", "-g", "daemon off;"]